import { MainNav } from "@/components/main-nav";
// import { MobileNav } from "@/components/mobile-nav";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { fontSans } from "@/lib/fonts";
import Link from "@/node_modules/next/link";
import { buttonVariants } from "@/components/ui/button";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/toggle";
import HeroPage from "./HeroPage/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
      >
        <body
          className={cn(
            "relative flex min-h-screen w-full flex-col justify-center scroll-smooth bg-background font-sans antialiased"
          )}
        >
          <div className="flex min-h-screen flex-col">
            <header className="container supports-backdrop-blur:bg-background/80 sticky top-0 z-40 w-full backdrop-blur bg-background border-b">
              <div className="flex h-20 items-center justify-between py-6">
                <MainNav />
                <nav>
                  <div className="md:flex">
                    <div className="flex gap-4">
                      <ModeToggle />
                      <Link
                        href="/login"
                        className={cn(
                          buttonVariants({ variant: "secondary", size: "sm" }),
                          "px-4"
                        )}
                      >
                        Login
                      </Link>
                    </div>
                  </div>
                </nav>
              </div>
            </header>
            <HeroPage />
          </div>
        
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
